-- seed.sql — Supabase local seed hook
--
-- Canonical seeder ของโปรเจกต์นี้คือ Drizzle: `pnpm db:seed` (scripts/seed.ts)
-- ซึ่ง type-safe และใช้ generateId() (UUID v7) เหมือน application layer
--
-- ไฟล์นี้เป็น no-op (comment-only) เพื่อให้ `supabase reset` ไม่ error
-- (config.toml [db.seed] sql_paths = ["./seed.sql"] บังคับให้มีไฟล์)
-- ข้อมูลจริงทั้งหมด (departments + categories + superadmin) อยู่ใน scripts/seed.ts
--
-- ลำดับการเตรียมข้อมูล local:
--   1. supabase start          (ยก Postgres stack)
--   2. pnpm db:push            (Drizzle → สร้าง schema)
--   3. pnpm db:seed            (Drizzle → ใส่ข้อมูลเริ่มต้น)
